version: '3'
services:

  mongodb_service:
    image: mongo:4.4.14-focal
    container_name: mongodb_service
    networks:
      kubernetes_network:
    volumes:
      - mongodb_service:/data/db
      - mongodb_service_config:/data/configdb
    ports:
      - 27016:27017

  # Nodejs
  authentication:
    image: authentication
    container_name: authentication
    build:
      context: .
      dockerfile: ./service/authentication/docker/Dockerfile
    networks:
      kubernetes_network:
    restart: always
    volumes:
      - ./service/authentication:/usr/apps/authentication
      - /usr/apps/authentication/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb_service

  users:
    image: users
    container_name: users
    build:
      context: .
      dockerfile: ./service/users/docker/Dockerfile
    networks:
      kubernetes_network:
    restart: always
    volumes:
      - ./service/users:/usr/apps/users
      - /usr/apps/users/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mongodb_service

#Docker Networks
networks:
  kubernetes_network:
    driver: bridge

#Volumes
volumes:
  mongodb_service:
    driver: local
  mongodb_service_config:
    driver: local
